name: Check for updates

on:
  schedule:
    - cron: '52 3/6 * * *'
  workflow_dispatch:

jobs:
  check:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: Endless External Data Checker
          GIT_COMMITTER_NAME: Endless External Data Checker
          GIT_AUTHOR_EMAIL: os@endlessos.org
          GIT_COMMITTER_EMAIL: os@endlessos.org
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # --never-fork is needed because the repository permissions
          # reported by the GitHub API claim that the user cannot push to the
          # repo, whereas in fact they can.
          args: |
            --verbose --update --never-fork com.google.Chrome.json
